Task
asakuno/mokumoku pull request #1
Opened 2022-11-15 17:14 UTC by asakuno

31期浅久野です。お忙しい中大変恐縮でございますが、PullRequestレビューのほどよろしくお願いします。
## 概要
7137ff2b95f75f500239789a7bce11f94ca663a7 に提案内容、実装方法を記載しました。

御確認のほどよろしくお願いします。

2022-11-17 03:15 UTC, Tsuchiya2 reviewed
提案ありがとうございます！LGTMです！
さて、次の「事業をエンジニアリングしよう ②実装」では実際の技術力を測定しますので、以下のspecが通るように実装をお願いします。提出時にテスト結果のスクリーンショットと選択した課題のプルリクエストに記載した上で提出してください。

https://esa-storage-tokyo.s3-ap-northeast-1.amazonaws.com/uploads/production/attachments/2315/2022/10/19/126058/5b3bbbf1-9bfe-4022-91dd-6a661ed99ead.zip

```
【実装方針】
- ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
- イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作できる。
- ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
- 女性限定イベントには女性のみが参加できる。
- 女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
- 女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。

【注意点】
- イベントが女性限定であるかを判定するカラムは"only_woman"とする
- ユーザーの性別登録のカラムは"gender"とする
- ユーザー登録時の性別のセレクト部分はenumを使って「LGTM・男性・女性」が表示される（その際に特に操作が無かればLGTMが選択される）
```

2022-11-19 17:22 UTC, asakuno commented
31期浅久野です。お忙しい中大変恐縮でございますが、PullRequestレビューのほどよろしくお願いします。

## 【実装方針】
- ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
こちら[f6d0f73](https://github.com/asakuno/mokumoku/pull/1/commits/f6d0f738251e9b0b6c2d3fb3f7ed73eb39a4031a)及び[47dc061](https://github.com/asakuno/mokumoku/pull/1/commits/47dc061b7e868bfcc25684b3521b2a2c6f0786ce)にて実装を行いました。

- イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作成できる。
- ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
こちら[33747ef](https://github.com/asakuno/mokumoku/pull/1/commits/33747ef16b487a42737a51f8741f2097babbb17d)及び[5eda699](https://github.com/asakuno/mokumoku/pull/1/commits/5eda699e996484b7c54ef8fccf118de2f8e4ab76)にて実装を行いました。


- 女性限定イベントには女性のみが参加できる。
- 女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
こちら[13013f4](https://github.com/asakuno/mokumoku/pull/1/commits/13013f4b09cc5dde267389874b556536cb0b82d8)にて実装を行いました。

- 女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。
こちら[2eadc2f](https://github.com/asakuno/mokumoku/pull/1/commits/2eadc2fe4a33303587931b8e8ba7fd99e24eb974)及び[ebfef1e](https://github.com/asakuno/mokumoku/pull/1/commits/ebfef1e6843bd53b0276b31f0995aee17332066e)にて実装を行いました。
<img width="992" alt="スクリーンショット 2022-11-20 1 58 16" src="https://user-images.githubusercontent.com/102037623/202863455-55d8e74f-1228-4b05-8a71-74e23bb3ff36.png">

以上ご確認のほどよろしくお願いいたします。

2022-11-20 04:20 UTC, masa-oh requested changes
テストは通っているので動作には問題ないと思いますが、コードの書き方の部分で何点か指摘をしましたので、修正をお願いします。

インスタンスメソッドに引数としてselfインスタンスを渡すような記述があったので、Railsのインスタンスメソッドの使い方を復習してみましょう。
また、複雑に考え過ぎてしまって、複雑な実装になっている部分があったので、より簡素で明快なコードを書けるように経験を積んでいけるといいですね！

2022-11-20 04:20 UTC, masa-oh commented on app/models/user.rb
> +    current_user.gender == "woman"
woman?メソッドはenumの機能により既に作成されており、オーバーライドする必要はないので、このメソッド定義は不要ですね。
また、current_userで対してではなく、userインスタンス（= self）のgenderを検証すべきですね。

2022-11-20 04:20 UTC, masa-oh commented on .gitignore
> +echo coverage >> .gitignore
ターミナルのコマンドをミスっているようです。
coverageディレクトリがpushされてしまっているので、gitignoreの表記を修正してください。

2022-11-20 04:20 UTC, masa-oh commented on app/views/events/_form.html.erb
> +  <% if event.woman?(current_user) %>
ログイン中のユーザーが女性かどうかを確認するのにeventは関係ないはずなので、以下のように書けるといいですね。
```<% if current_user.woman? %>```

2022-11-20 04:20 UTC, masa-oh commented on app/models/event.rb
> +    user.gender == "woman"
このメソッドは不要ではないでしょうか？
ユーザーが女性かどうかを確かめるメソッドは、eventモデルではなく、userモデルに書くべきです。
ユーザーモデル側には、女性かどうかを確かめるメソッドが既にあるはずですね！

2022-11-20 04:20 UTC, masa-oh commented on app/models/event.rb
> +    event.only_woman == true
このメソッドに対して引数を渡す必要はないですね。
eventインスタンス（=self）のonly_womanカラムがtrueかどうかを確かめたいので、引数なしで書き直してみてください。

また、`hoge == true`は`!!hoge`と書いた方がスマートですね。

2022-11-20 04:20 UTC, masa-oh commented on app/views/events/show.html.erb
> +                <% if @event.check(current_user) %>
event.checkというメソッドがどういう動きをするか、メソッド名から予想できないので、よりコードの読み手に伝わる書き方ができるといいですね。
ここは、「`@event`が女性限定である」かつ「`current_user`が女性である」の条件を満たしたときに表示される領域だと思うので、`&&`を使ってその通りに条件文を書くといいかと思います。

2022-11-20 04:20 UTC, masa-oh commented on app/models/event.rb
> +    check_woman(user) || check_others(user)
このメソッドは、eventとuserの両方に依存しており、かなり複雑ですね。
また、何をするメソッドなのかが命名から読み取れないので、シンプルに書くことを目指せるといいと思います。
view側のコード（`events/show.html.erb`）にコメントしていますが、「ユーザーが女性かどうか」というロジックの部分はuserモデルに分離できるので、eventモデルには「イベントが女性限定かどうか」を判別できるロジックがあれば十分ではないでしょうか。

2022-11-20 16:35 UTC, asakuno commented on app/models/user.rb
> +    current_user.gender == "woman"
こちら[cfa4369](https://github.com/asakuno/mokumoku/pull/1/commits/cfa4369fe3dca32a74b2275eff7441fef46c2dca)にて修正を行いました。

2022-11-20 16:36 UTC, asakuno commented on .gitignore
> +echo coverage >> .gitignore
こちら[2fc4878](https://github.com/asakuno/mokumoku/pull/1/commits/2fc4878dfc9aa542e8abd31e3b490e02c59f3fad)にて修正を行いましたが、coverageディレクトリ以下が変わらずpushされているようです。

2022-11-20 16:37 UTC, asakuno commented on app/views/events/_form.html.erb
> +  <% if event.woman?(current_user) %>
こちら[6abead9](https://github.com/asakuno/mokumoku/pull/1/commits/6abead92b9bba22b803c4e25b666ba2fadf185b0)にて修正を行いました。

2022-11-20 16:37 UTC, asakuno commented on app/models/event.rb
> +    user.gender == "woman"
こちら[c2a9b85](https://github.com/asakuno/mokumoku/pull/1/commits/c2a9b851f8556b1cea3bd2afc4c0ab627e4ac7c7)にて修正を行いました。

2022-11-20 16:38 UTC, asakuno commented on app/models/event.rb
> +    event.only_woman == true
こちら[ee7acc8](https://github.com/asakuno/mokumoku/pull/1/commits/ee7acc80c5d6779061a29fcbc609df0f2f52701c)にて修正を行いました。

2022-11-20 16:39 UTC, asakuno commented on app/views/events/show.html.erb
> +                <% if @event.check(current_user) %>
こちら[0526864](https://github.com/asakuno/mokumoku/pull/1/commits/0526864784be8ae48185a6cca8765e5c90c41060)にて修正を行いました。

2022-11-20 16:42 UTC, asakuno commented on app/models/event.rb
> +    check_woman(user) || check_others(user)
こちらも[0526864](https://github.com/asakuno/mokumoku/pull/1/commits/0526864784be8ae48185a6cca8765e5c90c41060)にて修正を行いましたが、ビューに直接条件式を書き込む場合とモデルにメソッドを定義する場合とでどのように差別化したらよろしいでしょうか。

2022-11-20 23:59 UTC, busitora commented on app/views/events/show.html.erb
> +                <% if @event.check(current_user) %>
https://github.com/asakuno/mokumoku/pull/1/commits/0526864784be8ae48185a6cca8765e5c90c41060#diff-4762449bd030fb46d090146948477da2d4f64633de7f0561094a45b63a5e15fbR100

なかんじで、他にノイズが有る場合レビュワーが見やすいようにすると更にいいですね

2022-11-21 03:07 UTC, Tsuchiya2 commented on .gitignore
> +echo coverage >> .gitignore
/coverage と記載するとどうなりますかね？

2022-11-21 03:15 UTC, Tsuchiya2 commented on app/models/event.rb
> +    check_woman(user) || check_others(user)
考え方やチームによって異なりますが、個人的にはモデルやデコレーターに寄せておきたいですね。ビュー側でコードを読んだ際にどんなことをするのか、どんな値を期待しているのかが分かるようにしておきたいですね。

2022-11-21 03:16 UTC, Tsuchiya2 reviewed
LGTMです！🌟

2022-11-21 11:52 UTC, merged